FROM python:latest

RUN pip install django
RUN pip install Pillow
RUN pip install djangorestframework
RUN pip install django-filter
RUN pip install drf-yasg
RUN pip install reportlab

RUN pip install django_compressor
RUN pip install django-libsass

RUN pip install xhtml2pdf

RUN pip install pdfkit 

RUN pip install djoser

RUN pip install djangorestframework_simplejwt
RUN pip install dj-rest-auth
RUN pip install allauth-django