FROM node:16.13.0

RUN yarn add axios

RUN yarn add react-router-dom

RUN yarn add sass

RUN yarn add libphonenumber-js

RUN yarn add react-dropzone

RUN yarn add react-hook-form

RUN yarn add react-select

RUN yarn add uuid

RUN yarn add @mui/material @emotion/react @emotion/styled