version: '3'

services:
  
  reverse-proxy:
    container_name: reverse-proxy
    hostname: reverse-proxy
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static_volume:/backend/static
    
  # certbot:
  #   container_name: certbot
  #   hostname: certbot
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
    

  frontend:
      image: vicjgb/craftshake-frontend:latest
      build: 
        context: ./frontend
      hostname: frontend  
      container_name: frontend 
      environment:
        HOST: "0.0.0.0"  
        REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      depends_on:   
        - backend  

  backend:
      image: vicjgb/craftshake-backend:latest
      hostname: backend
      container_name: backend
      environment:
        POSTGRES_URL: ${POSTGRES_URL}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB:  ${POSTGRES_DB}
        TELEGRAM_BOT_NAME: ${TELEGRAM_BOT_NAME}
        TELEGRAM_BOT_KEY: ${TELEGRAM_BOT_KEY}
        GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
        GOOGLE_SECRET: ${GOOGLE_SECRET}
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_STORAGE_BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
        SECRET_KEY: ${SECRET_KEY}
        ENVIRONMENT: ${ENVIRONMENT}
      volumes:
        - static_volume:/usr/local/lib/python3.10/site-packages/django/contrib/admin/static

  debug:
    image: praqma/network-multitool
    container_name: debug
    hostname: debug
    tty: true


volumes:
  static_volume: