version: '3'

services:
  
  # reverse-proxy:
  #   container_name: reverse-proxy
  #   hostname: reverse-proxy
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  #     - ./certbot/www:/var/www/certbot/:ro
  #     - ./certbot/conf/:/etc/nginx/ssl/:ro
    
  # certbot:
  #   container_name: certbot
  #   hostname: certbot
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
    

  frontend:
      user: ${UID}:${GID} 
      image: node:16.15.1
      build: 
        context: ./frontend
      hostname: frontend  
      container_name: frontend 
      ports:
        - "3000:3000"
      environment:
        HOST: "0.0.0.0"
      tty: true 
      volumes:
        - ./frontend:/app  
      depends_on:   
        - backend  

  backend:
      user: ${UID}:${GID}
      image: python:3.10.9
      build:
          context: ./Cocktails
      hostname: backend
      container_name: backend
      ports:
        - "8000:8000"
      environment:
        POSTGRES_URL: ${POSTGRES_URL}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB:  ${POSTGRES_DB}
      tty: true
      volumes:
        - ./Cocktails:/app