version: '3'

services:

  frontend:
      user: ${UID}:${GID} #имя пользователя и группы в нутри докера, равные мимени пользователя на локальной машине
      image: node:16.15.1
      # command: yarn start ./app/cocktails/ 
      build: 
        context: ./frontend
      hostname: frontend  #Кастомное навание хоста
      container_name: frontend #имя контейнера которое понимет докерв
      ports:
        - "3000:3000"
      environment:
        HOST: "0.0.0.0"
      tty: true #контейнер живет до явногой команды отключиться
      volumes:
        - ./frontend:/app  #общая папка для локальной машини и контейнера
      depends_on:   #зависимость он другого докера
        - backend  

  backend:
      user: ${UID}:${GID}
      image: python:3.10.9
      command: python /app/manage.py runserver 0.0.0.0:8000
      build:
          context: ./Cocktails
      hostname: backend
      container_name: backend
      ports:
        - "8000:8000"
      environment:
        POSTGRES_URL: ${POSTGRES_URL}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_DB:  ${POSTGRES_DB}
      tty: true
      volumes:
        - ./Cocktails:/app
      depends_on:
        - database

  # database:
  #   # user: ${UID?err}:${GID?err}
  #   image: postgres:latest
  #   hostname: database
  #   container_name: database
  #   ports:
  #     - "5432:5432"
  #   tty: true
  #   volumes:
  #     - ./database:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB:  ${POSTGRES_DB}
