# Generated by Django 4.0.4 on 2022-05-22 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='E-mail')),
                ('is_current_customer', models.BooleanField(default=True, verbose_name='Current customer')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost price')),
                ('discription', models.TextField(blank=True, max_length=500, verbose_name='About')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Sale price')),
                ('photo', models.ImageField(blank=True, upload_to='Product photo', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='TotalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_vat', models.BooleanField(default=True, verbose_name='With VAT')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='TOTAL')),
                ('date', models.DateField(verbose_name='Date')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.customer')),
            ],
            options={
                'verbose_name': 'Total bill',
                'verbose_name_plural': 'Total bills',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_current_menu', models.BooleanField(default=True, verbose_name='Current menu')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.customer')),
                ('product', models.ManyToManyField(blank=True, related_name='product_in_menu', to='counter.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_vat', models.BooleanField(default=False, verbose_name='With VAT')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='TOTAL')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.customer')),
                ('product_in_bill', models.ManyToManyField(to='counter.menu', verbose_name='Products')),
                ('total_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.totalbill', verbose_name='Total bill')),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
            },
        ),
    ]
