# Generated by Django 4.0.4 on 2022-05-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='product',
        ),
        migrations.CreateModel(
            name='MenuPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Sale price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.product')),
            ],
            options={
                'verbose_name': 'Position for menu',
                'verbose_name_plural': 'Positions for menu',
            },
        ),
        migrations.CreateModel(
            name='ManagerOfPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.customer')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='position',
            field=models.ManyToManyField(blank=True, related_name='position_in_menu', to='counter.menuposition', verbose_name='Position'),
        ),
    ]
