# Generated by Django 4.0.4 on 2022-05-24 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0002_remove_menu_product_menuposition_managerofplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='position',
        ),
        migrations.AddField(
            model_name='menuposition',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.menu', verbose_name='Menu'),
            preserve_default=False,
        ),
    ]
