# Generated by Django 4.0.4 on 2022-05-24 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0003_remove_menu_position_menuposition_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='menu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_in_menu', to='counter.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='menuposition',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.product', verbose_name='Product'),
        ),
    ]
