# Generated by Django 4.0.4 on 2022-05-25 08:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0005_order_remove_totalbill_customer_delete_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2022, 5, 25), verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='order',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.menu', verbose_name='Menu'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Amount price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.order', verbose_name='Order')),
                ('position', models.ManyToManyField(related_name='menu_position', to='counter.menuposition', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
    ]
