# Generated by Django 4.0.4 on 2022-05-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0006_order_date_order_menu_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Product_photo', verbose_name='Photo'),
        ),
    ]
