# Generated by Django 4.0.4 on 2022-05-25 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0008_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='position',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.menuposition', verbose_name='Position'),
            preserve_default=False,
        ),
    ]
