# Generated by Django 4.0.4 on 2022-05-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0010_alter_order_date_invoice_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='counter.customer', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_in_invoice', to='counter.invoice', verbose_name='Invoice'),
        ),
    ]
