# Generated by Django 4.0.4 on 2022-05-31 13:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0011_alter_order_customer_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 13, 35, 17, 505794, tzinfo=utc), verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 31, 13, 35, 17, 506234, tzinfo=utc), verbose_name='Date'),
        ),
    ]
