# Generated by Django 4.0.4 on 2022-09-14 12:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0012_alter_invoice_date_alter_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=50, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=14, verbose_name='Phone')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='E-mail')),
                ('is_current_place', models.BooleanField(default=True, verbose_name='Current place')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuposition',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='counter.invoice', verbose_name='Invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='counter.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, default='../media/cocktailDefault.jpeg', upload_to='Product_photo', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='counter.place', verbose_name='Place'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.place'),
        ),
        migrations.AddField(
            model_name='order',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='place_order', to='counter.place', verbose_name='Place'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerofplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counter.place'),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
