# Generated by Django 4.0.4 on 2022-09-14 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0013_place_remove_invoice_customer_remove_menu_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuposition',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_in_menu', to='counter.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.menuposition', verbose_name='Position'),
        ),
    ]
