# Generated by Django 4.0.4 on 2022-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0017_orderitem_name_alter_orderitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.CharField(blank=True, default='unknow name', max_length=50, verbose_name='Name'),
        ),
    ]
