# Generated by Django 4.0.4 on 2022-09-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0018_alter_orderitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='counter.menuposition', verbose_name='Position'),
        ),
    ]
