# Generated by Django 4.0.4 on 2022-09-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0019_alter_orderitem_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerofplace',
            name='discription',
            field=models.TextField(blank=True, max_length=500, verbose_name='About'),
        ),
    ]
