# Generated by Django 4.0.4 on 2022-09-14 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0020_managerofplace_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerofplace',
            old_name='discription',
            new_name='description',
        ),
    ]
