# Generated by Django 4.0.4 on 2022-09-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0021_rename_discription_managerofplace_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.CharField(default='No state', max_length=10, verbose_name='State'),
        ),
    ]
