name: Deploy to Hutzner

on:
 
  push:
    branches: [ main ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    # - name: Cache dependencies
    #   id: cache-deps-backend
    #   uses: actions/cache@v2
    #   with:
    #     path: Cocktails/
    #     key: ${{ runner.os }}-backend-{{ hashFiles('Cocktails/requirements.txt') }}
    #     restore-keys: ${{ runner.os }}-backend-

    # - name: Cache dependencies
    #   id: cache-deps-frontend
    #   uses: actions/cache@v2
    #   with:
    #     path: frontend/
    #     key: ${{ runner.os }}-frontend-{{ hashFiles('frontend/cocktails/package-lock.json') }}
    #     restore-keys: ${{ runner.os }}-frontend-

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin


    - name: Build, tag, and push image to DockerHub
      env:
        DOCKER_BACKEND_REPOSITORY:  craftshake-backend
        DOCKER_FRONTEND_REPOSITORY:  craftshake-frontend 
      run: |
        cd Cocktails/ 
        docker build --no-cache -t craftshake-backend .
        docker tag craftshake-backend vicjgb/craftshake-backend:latest
        docker push vicjgb/craftshake-backend
        cd ../frontend/ 
        docker build --no-cache -t craftshake-frontend .
        docker tag craftshake-frontend vicjgb/craftshake-frontend:latest
        docker push vicjgb/craftshake-frontend

    - name: Create .env file
      run: echo ${{ secrets.ENV_FILE }} > .env
    
    - name: Pull on Hutzner backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HUTZNER_SERVER_IP }}
        username: ${{ secrets.HUTZNER_SERVER_USERNAME }}
        key: ${{ secrets.HUTZNER_SERVER_SSH_KEY }}
        script: |
          if docker ps -a --filter "name=craftshake-backend" --format '{{.Names}}' | grep -q "craftshake-backend"; then
             docker stop craftshake-backend
             docker rm craftshake-backend
          fi
          if docker ps -a --filter "name=craftshake-frontend" --format '{{.Names}}' | grep -q "craftshake-frontend"; then
             docker stop craftshake-frontend
             docker rm craftshake-frontend
          fi
          
          docker pull vicjgb/craftshake-backend:latest
          docker pull vicjgb/craftshake-frontend:latest
          
          docker run --detach --name craftshake-frontend -p 3000:3000 vicjgb/craftshake-frontend:latest
          docker run --detach --name craftshake-backend -p 8000:8000 --env-file=.env  vicjgb/craftshake-backend:latest

      

